services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: exchange-db
      POSTGRES_USER: exchange-user
      POSTGRES_PASSWORD: exchange-password
    ports:
      - "5432:5432"

  postgres-test:
    image: postgres:latest
    environment:
      POSTGRES_DB: exchange-db-test
      POSTGRES_USER: exchange-user
      POSTGRES_PASSWORD: exchange-password
    ports:
      - "5433:5432"